Update mactool

diff --git a/mactool b/mactool
--- a/mactool
+++ b/mactool
@@ -26,71 +26,71 @@ LB="\e[36m"
 NC="\e[0m"
 
 
-if ! (command -v macchanger >/dev/null 2>&1 && command -v figlet >/dev/null 2>&1); then
+if ! (command -v sudo >/dev/null 2>&1 && command -v macchanger >/dev/null 2>&1 && command -v figlet >/dev/null 2>&1); then
 
-       pkgs=(macchanger figlet)
+       pkgs=(sudo macchanger figlet)
 
        if [[ $(command -v apt) ]]; then
                 if ! apt install -y ${pkgs[@]}; then
-                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}'${pkgs[@]}'${NC}"
+                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                 exit 1
                 fi
         elif [[ $(command -v pacman) ]]; then
                 if ! pacman -Sy --noconfirm --needed --overwrite "*" ${pkgs[@]}; then
-                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}'${pkgs[@]}'${NC}"
+                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                 exit 1
                 fi
         elif [[ $(command -v dnf) ]]; then
                 if ! dnf install -y --allowerasing ${pkgs[@]}; then
-                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}'${pkgs[@]}'${NC}"
+                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                 exit 1
                 fi
         elif [[ $(command -v yum) ]]; then
                 if ! yum install -y ${pkgs[@]}; then
-                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}'${pkgs[@]}'${NC}"
+                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                 exit 1
                 fi
         elif [[ $(command -v xbps-install) ]]; then
                 if ! xbps-install -Sy -f -y "*" ${pkgs[@]}; then
-                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}'${pkgs[@]}'${NC}"
+                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                 exit 1
                 fi
         elif [[ $(command -v zypper) ]]; then
                 if ! zypper install ${pkgs[@]}; then
-                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}'${pkgs[@]}'${NC}"
+                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                 exit 1
                 fi
         elif [[ $(command -v apk) ]]; then
                 if ! apk add --no-cache ${pkgs[@]}; then
-                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}'${pkgs[@]}'${NC}"
+                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                 exit 1
                 fi
         elif [[ $(command -v emerge) ]]; then
                 if ! emerge -v --oneshot --keep-going ${pkgs[@]}; then
-                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}'${pkgs[@]}'${NC}"
+                echo -e "\n${RED}[${NC}-${RED}] Could not install: ${ORANGE}'${pkgs[@]}'${NC}"
                 exit 1
                 fi
         else
-                echo -e "\n${RED}[${NC}-${RED}]${NC} Not common: ${RED}Unsuported pkg manager, please install: ${ORANGE}'${pkgs[@]}'${NC}"
+                echo -e "\n${RED}[${NC}-${RED}] Unsuported package manager, install: ${ORANGE}'${pkgs[@]}'${NC}"
                 exit 1
         fi
 fi
 
 # Banner
 
-echo -e "${GREEN}" && figlet MacTool
-echo -n -e "${BLUE}v1.0.0.2 ${LB}-->${GREEN} neptune's layer 2 anonymation util"
+echo -e "${GREEN}" && figlet mactool
+echo -n -e "${BLUE}v2.0.0 ${LB}-->${GREEN} MAC Address util${NC}"
 echo -e "\n"
-echo -e "${ORANGE}[${BLUE}*${ORANGE}] ${YELLOW}Coded By: ${ORANGE}gmasterone@duck.com ${NC}"
+echo -e "${ORANGE}[${BLUE}*${ORANGE}] ${YELLOW}Coded By: ${ORANGE}archnon@protonmail.com ${NC}"
 
 usage(){
-echo -e "\n${ORANGE}[${YELLOW}*${ORANGE}]${GREEN} usage: ${P}sudo mactool ${NC}<${GREEN}option${NC}>${NC}"
-echo -e "\n${BLUE}[${ORANGE}1${BLUE}] ${ORANGE}change${NC}: ${NC}${GREEN}Change MAC Addr of device${NC}"
-echo -e "\n${BLUE}[${ORANGE}2${BLUE}] ${ORANGE}enable${NC}: ${GREEN}Enable MAC changing on boot${NC}"
-echo -e "\n${BLUE}[${ORANGE}3${BLUE}] ${ORANGE}disable${NC}: ${RED}Disable ${GREEN}MAC changing on boot${NC}"
-echo -e "\n${BLUE}[${ORANGE}4${BLUE}] ${ORANGE}daemon${NC}: ${GREEN}Daemonize MAC changing of device${NC}"
-echo -e "\n${BLUE}[${ORANGE}5${BLUE}] ${ORANGE}restore: ${GREEN}Restore Device's MAC${NC}"
-echo -e "\n${BLUE}[${ORANGE}6${BLUE}] ${ORANGE}show${NC}: ${GREEN}Show Available Devices${NC}"
+echo -e "\n${ORANGE}[${YELLOW}*${ORANGE}]${GREEN} usage: ${P}mactool ${NC}<${GREEN}COMMAND${NC}> ${NC}<${GREEN}OPTIONS${NC}>${NC}"
+echo -e "\n${BLUE}[${ORANGE}1${BLUE}] ${ORANGE}-c${BLUE}|${ORANGE}--change-mac${NC}: ${NC}${GREEN}Change MAC of device${NC}"
+echo -e "\n${BLUE}[${ORANGE}2${BLUE}] ${ORANGE}-e${BLUE}|${ORANGE}--enable-boot${NC}: ${GREEN}Enable MAC changing on boot${NC}"
+echo -e "\n${BLUE}[${ORANGE}3${BLUE}] ${ORANGE}-d${BLUE}|${ORANGE}--disable-boot${NC}: ${RED}Disable ${GREEN}MAC changing on boot${NC}"
+echo -e "\n${BLUE}[${ORANGE}4${BLUE}] ${ORANGE}-b${BLUE}|${ORANGE}--in-background-change${NC} <${P}arg${NC}>: ${GREEN}Daemonize MAC changing of device${NC}"
+echo -e "\n${BLUE}[${ORANGE}5${BLUE}] ${ORANGE}-r${BLUE}|${ORANGE}--restore-mac: ${GREEN}Restore Device's MAC${NC}"
+echo -e "\n${BLUE}[${ORANGE}6${BLUE}] ${ORANGE}-l${BLUE}|${ORANGE}--list-available-devices${NC}: ${GREEN}Show Available Devices${NC}"
 }
 
 change(){
@@ -229,7 +229,7 @@ echo -e "\n${RED}[${NC}-${RED}]${NC} Kill them by running: ${RED}sudo pkill -9 m
 while [ $# -gt 0 ]; do
         case $1 in
 
-        change|--device|-d)
+        -c|-change-mac|--change-mac)
         mode=1
         device=$2
 
@@ -259,7 +259,7 @@ while [ $# -gt 0 ]; do
 
         ;;
 
-        --enable|enable)
+        -e|-enable-boot|--enable-boot)
         mode=2
         device=$2
 
@@ -289,7 +289,7 @@ while [ $# -gt 0 ]; do
 
         ;;
 
-        --disable|disable)
+        -d|-disable-boot|--disable-boot)
         mode=3
         device=$3
 
@@ -309,7 +309,7 @@ while [ $# -gt 0 ]; do
 
         ;;
 
-        --daemon|daemon)
+        -b|-in-background-change|--in-background-change)
         mode=4
         i=$2
         device=$3
@@ -352,7 +352,7 @@ while [ $# -gt 0 ]; do
 
         ;;
 
-        restore|--reset|reset)
+        -r|-restore-mac|--restore-mac)
         mode=5
         device=$2
 
@@ -384,7 +384,7 @@ while [ $# -gt 0 ]; do
 
         ;;
 
-        --show-devices|show)
+        -l|-list-available-devices|--list-available-devices)
         mode=6
 
         echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${GREEN} Available Devices${NC}:" && ip link || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}could not show devices${NC}"
